export const mockCustomers = [
    {
      id: "cust-001",
      name: "Acme Corporation",
      phone: "+62-21-5551234",
      address: "Jl. Sudirman No. 123, Jakarta Pusat",
      projectCount: 3,
    },
    {
      id: "cust-002",
      name: "Globex Industries",
      phone: "+62-21-5555678",
      address: "Jl. Gatot Subroto No. 456, Jakarta Selatan",
      projectCount: 0,
    },
    {
      id: "cust-003",
      name: "Soylent Corp",
      phone: "+62-22-5559876",
      address: "Jl. Asia Afrika No. 789, Bandung",
      projectCount: 2,
    },
    {
      id: "cust-004",
      name: "Initech",
      phone: "+62-31-5554321",
      address: "Jl. Pemuda No. 101, Surabaya",
      projectCount: 1,
    },
    {
      id: "cust-005",
      name: "Umbrella Corporation",
      phone: "+62-21-5557890",
      address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
      projectCount: 0,
    },
    {
        id: "cust-006",
        name: "Umbrella Corporation",
        phone: "+62-21-5557890",
        address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
        projectCount: 0,
      },
      {
        id: "cust-007",
        name: "Umbrella Corporation",
        phone: "+62-21-5557890",
        address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
        projectCount: 0,
      },
      {
        id: "cust-008",
        name: "Umbrella Corporation",
        phone: "+62-21-5557890",
        address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
        projectCount: 0,
      },
      {
        id: "cust-009",
        name: "Umbrella Corporation",
        phone: "+62-21-5557890",
        address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
        projectCount: 0,
      },
      {
        id: "cust-010",
        name: "Umbrella Corporation",
        phone: "+62-21-5557890",
        address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
        projectCount: 0,
      },
      {
        id: "cust-011",
        name: "Umbrella Corporation",
        phone: "+62-21-5557890",
        address: "Jl. MH Thamrin No. 202, Jakarta Pusat",
        projectCount: 0,
      },
  ]
  